import { Matkasse } from "@/components/MatkasseCard";

export const matkasser: Matkasse[] = [
  {
    slug: "hellofresh",
    navn: "HelloFresh",
    tagline: "Størst utvalg – 25+ retter å velge mellom, enkel app og fleksibel levering",
    rating: 4.6,
    antalltester: 1842,
    prisPerPorsjon: 89,
    ukentligPris: 356,
    leverandor: "HelloFresh",
    logoUrl: "https://logo.clearbit.com/hellofresh.no",
    fallbackInitials: "HF",
    fallbackColor: "#e53e3e",
    badge: "best",
    fordeler: [
      "25+ retter å velge mellom ukentlig",
      "Lett å pause eller avslutte",
      "Kalorismarte og glutenfrie valg",
      "Rask levering i hele landet",
    ],
    ulemper: [
      "Mye emballasje",
      "Standardpris litt over snittet",
    ],
    affiliateUrl: "https://track.adtraction.com/t/t?a=1234567&as=CHANNEL&t=2&tk=",
    passerFor: "Par og familier som vil ha variasjon uten å planlegge",
    tilbud: "Opptil 60% rabatt på de første ukene",
    bindingstid: "Ingen",
    levering: "Hele landet",
    ctaText: "Prøv HelloFresh gratis",
  },
  {
    slug: "godtlevert",
    navn: "Godtlevert",
    tagline: "Norsk klassiker med 80+ retter ukentlig og 6 ulike kassestørrelser",
    rating: 4.4,
    antalltester: 1203,
    prisPerPorsjon: 84,
    ukentligPris: 336,
    leverandor: "Godtlevert",
    logoUrl: "https://logo.clearbit.com/godtlevert.no",
    fallbackInitials: "GL",
    fallbackColor: "#276749",
    badge: "fleksibel",
    fordeler: [
      "6 størrelser (1–6 pers.)",
      "80+ retter å velge blant per uke",
      "Kortreiste råvarer, norsk fokus",
      "Godt for enslige",
    ],
    ulemper: [
      "Ikke tilgjengelig overalt",
      "Appen kan oppleves treg",
    ],
    affiliateUrl: "https://track.adtraction.com/t/t?a=7654321&as=CHANNEL&t=2&tk=",
    passerFor: "Alle husholdningsstørrelser som vil støtte norsk mat",
    tilbud: "50% rabatt første uke",
    bindingstid: "Ingen",
    levering: "Sør- og Østlandet",
    ctaText: "Få tilbud fra Godtlevert",
  },
  {
    slug: "adams-matkasse",
    navn: "Adams Matkasse",
    tagline: "Kjent for kortreist norsk kjøtt og fisk – og utmerket allergitilpasning",
    rating: 4.3,
    antalltester: 987,
    prisPerPorsjon: 91,
    ukentligPris: 364,
    leverandor: "Adams Matkasse",
    logoUrl: "https://logo.clearbit.com/adamsmatkasse.no",
    fallbackInitials: "AM",
    fallbackColor: "#c05621",
    fordeler: [
      "Glutenfri og vegetar-alternativer",
      "Norsk kjøtt og fisk i fokus",
      "Utmerket for allergikere",
    ],
    ulemper: [
      "Dyrere per porsjon",
      "Færre retter å velge mellom",
    ],
    affiliateUrl: "https://track.adtraction.com/t/t?a=1122334&as=CHANNEL&t=2&tk=",
    passerFor: "Allergikere og de som vil ha norske råvarer",
    bindingstid: "Ingen",
    levering: "Hele landet",
    ctaText: "Få tilbud fra Adams Matkasse",
  },
];
