import { Matkasse } from "@/components/MatkasseCard";

export const matkasser: Matkasse[] = [
  {
    slug: "hellofresh",
    navn: "HelloFresh",
    tagline: "Størst utvalg i Norge – 25+ retter per uke, enkel app og fleksibel levering",
    rating: 4.6,
    antalltester: 1842,
    prisPerPorsjon: 89,
    ukentligPris: 356,
    leverandor: "HelloFresh",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/HelloFresh_Logo.svg/320px-HelloFresh_Logo.svg.png",
    badge: "best",
    fordeler: [
      "25+ retter å velge mellom ukentlig",
      "Lett å pause eller avslutte",
      "Kalorismarte og glutenfrie valg",
      "Rask levering i hele Norge",
    ],
    ulemper: [
      "Mye emballasje og plast",
      "Standardpris noe over snittet",
    ],
    affiliateUrl: "https://track.adtraction.com/t/t?a=1234567&as=CHANNEL&t=2&tk=",
    passerFor: "Par og familier som vil ha variasjon uten å planlegge selv",
    tilbud: "Nå: Opptil 60% rabatt på de første 4 ukene",
    bindingstid: "Ingen",
    levering: "Hele Norge",
  },
  {
    slug: "godtlevert",
    navn: "Godtlevert",
    tagline: "Norsk klassiker med 80+ retter, kortreiste råvarer og 6 ulike kassestørrelser",
    rating: 4.4,
    antalltester: 1203,
    prisPerPorsjon: 84,
    ukentligPris: 336,
    leverandor: "Godtlevert",
    logoUrl: "https://www.godtlevert.no/assets/images/logo.svg",
    badge: "fleksibel",
    fordeler: [
      "6 ulike kassestørrelser (1–6 pers.)",
      "80+ retter i uka å velge blant",
      "Fokus på norske og kortreiste råvarer",
      "Godt alternativ for enslige",
    ],
    ulemper: [
      "Levering ikke tilgjengelig alle steder",
      "Appen kan oppleves som treg",
    ],
    affiliateUrl: "https://track.adtraction.com/t/t?a=7654321&as=CHANNEL&t=2&tk=",
    passerFor: "Alle husholdningsstørrelser som vil støtte norsk landbruk",
    tilbud: "Prøv første uke med 50% rabatt",
    bindingstid: "Ingen",
    levering: "Sør- og Østlandet",
  },
  {
    slug: "adams-matkasse",
    navn: "Adams Matkasse",
    tagline: "Den norske klassikeren – kjent for kortreist kjøtt, fisk og allergitilpasning",
    rating: 4.3,
    antalltester: 987,
    prisPerPorsjon: 91,
    ukentligPris: 364,
    leverandor: "Adams Matkasse",
    logoUrl: "https://www.adamsmatkasse.no/images/logo.png",
    fordeler: [
      "Glutenfri og vegetaralternativ",
      "Norsk kjøtt og fisk i fokus",
      "Utmerket for allergikere",
      "Sterk kundeservice",
    ],
    ulemper: [
      "Dyrere per porsjon enn konkurrentene",
      "Færre retter å velge mellom",
    ],
    affiliateUrl: "https://track.adtraction.com/t/t?a=1122334&as=CHANNEL&t=2&tk=",
    passerFor: "Allergikere og de som setter pris på kortreiste norske råvarer",
    bindingstid: "Ingen",
    levering: "Hele Norge",
  },
];
